# Site settings
title: digitalbs
email: schneid.brian@gmail.com
description: digitalbs contains my thoughts and ideas in the digital space, as well as the homepage for my git projects. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://digitalbs.github.io" # the base hostname & protocol for your site
twitter_username: digital_bs
github_username:  digitalbs

# Build settings
markdown: kramdown
